# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: powerstream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'powerstream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11powerstream.proto\"\xad\x02\n\x11PowerStreamHeader\x12\x12\n\x05pdata\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x10\n\x03src\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x11\n\x04\x64\x65st\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x15\n\x08\x63md_func\x18\x08 \x01(\x05H\x03\x88\x01\x01\x12\x13\n\x06\x63md_id\x18\t \x01(\x05H\x04\x88\x01\x01\x12\x15\n\x08\x64\x61ta_len\x18\n \x01(\x05H\x05\x88\x01\x01\x12\x10\n\x03seq\x18\x0e \x01(\x05H\x06\x88\x01\x01\x12\x12\n\x05\x66rom_\x18\x17 \x01(\tH\x07\x88\x01\x01\x12\x16\n\tdevice_sn\x18\x19 \x01(\tH\x08\x88\x01\x01\x42\x08\n\x06_pdataB\x06\n\x04_srcB\x07\n\x05_destB\x0b\n\t_cmd_funcB\t\n\x07_cmd_idB\x0b\n\t_data_lenB\x06\n\x04_seqB\x08\n\x06_from_B\x0c\n\n_device_sn\";\n\x18PowerStreamSendHeaderMsg\x12\x1f\n\x03msg\x18\x01 \x03(\x0b\x32\x12.PowerStreamHeader\"\xd8\x01\n\x1cPowerStreamInverterHeartbeat\x12\x1c\n\x0fpv1_input_watts\x18\x13 \x01(\x05H\x00\x88\x01\x01\x12\x1c\n\x0fpv2_input_watts\x18\x18 \x01(\x05H\x01\x88\x01\x01\x12\x1d\n\x10inv_output_watts\x18& \x01(\x05H\x02\x88\x01\x01\x12\x14\n\x07\x62\x61t_soc\x18\x1f \x01(\rH\x03\x88\x01\x01\x42\x12\n\x10_pv1_input_wattsB\x12\n\x10_pv2_input_wattsB\x13\n\x11_inv_output_wattsB\n\n\x08_bat_socb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'powerstream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POWERSTREAMHEADER']._serialized_start=22
  _globals['_POWERSTREAMHEADER']._serialized_end=323
  _globals['_POWERSTREAMSENDHEADERMSG']._serialized_start=325
  _globals['_POWERSTREAMSENDHEADERMSG']._serialized_end=384
  _globals['_POWERSTREAMINVERTERHEARTBEAT']._serialized_start=387
  _globals['_POWERSTREAMINVERTERHEARTBEAT']._serialized_end=603
# @@protoc_insertion_point(module_scope)
